name: HCNM
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - numpy>=1.24.0
  - scikit-learn>=1.3.0
  - scipy>=1.10.0
  - pandas>=2.0.0
  - tqdm>=4.65.0
  - python=3.9.19
  - pytorch=2.4.1
